version: '3.9'
services:
  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: authenticationService/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8084:8084
    depends_on:
      - mysqlService


  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"


networks:
  mynetwork:
    driver: bridge