FROM openjdk:11
WORKDIR usr/lib
ADD ./target/vehicleDescriptionService-0.0.1-SNAPSHOT.jar /usr/lib/vehicleDescriptionService-0.0.1-SNAPSHOT.jar
ENTRYPOINT["java","-jar","vehicleDescriptionService-0.0.1-SNAPSHOT.jar"]